### ISSUE TITLE
Suppress unused variable declarations warning

### ISSUE THREAD

**Issue by briankariuki** [Valian/live_vue#25]
```
12.26                                                                                                                               
12.26 > build                                                                                                                       
12.26 > vue-tsc && vite build                                                                                                       
12.26                                                                                                                               
36.97 vue/components/GoalAnimation.vue(18,7): error TS6133: 'emit' is declared but its value is never read.
37.65 ** (exit) 2
37.65     (mix 1.17.0) lib/mix/tasks/cmd.ex:74: Mix.Tasks.Cmd.run/1
37.65     (mix 1.17.0) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
37.65     (mix 1.17.0) lib/mix/task.ex:561: Mix.Task.run_alias/6
37.65     (mix 1.17.0) lib/mix/cli.ex:96: Mix.CLI.run_task/2
37.65     /usr/local/bin/mix:2: (file)
------
Dockerfile:82
--------------------
  80 |     
  81 |     # compile assets
  82 | >>> RUN cd apps/mechi_web && mix assets.deploy
  83 |     
  84 |     # Compile the release
```

How can I suppress such errors when building for a release? This works in dev and does not error out

**Comment by Valian** [comment]
Hi @briankariuk! Either fix an error, disable check for that particular line or disable check for builds entirely. 

To disable that check, simply remove `vue-tsc` from package.json scripts section.
